title: "Trivia demo"
# remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme
#markdown: kramdown 
#kramdown: 
#   math_engine: mathjax 
#   math_engine_opts: 
#     preview: false
#defaults:
#  - scope:
#      path: ""
#      type: "pages"
#    values:
#      layout: "default"
     
